permalink: /log/:title/
relative_permalinks: false
markdown: kramdown
# excerpt_separator: "\n\n\n"

name: "Relish 2014: Calendar for HOPE."
url: http://calendarforhope.com
description: "9th annual charity calendar by zando &amp; jot (formerly vrse design inc.). all proceeds go to the University of Alberta's HOPE program."
timezone: America/Edmonton

exclude: [.gitignore, .editorconfig, Gemfile, Gemfile.lock, README.md]
